### ISSUE TITLE
Ch6 comments

### ISSUE THREAD

**Issue by stefanv** [elegant-scipy/elegant-scipy#146]
I'll add them here as I progress:
- [x] Instead of saying "pick up a linear algebra textbook", perhaps let readers watch Lecture 1 from http://ocw.mit.edu/courses/mathematics/18-06-linear-algebra-spring-2010/video-lectures/
- [x] When describing vector / matrix notation, give examples.  Vectors are written as **x**, while matrices use capital letters as in X.
- [x] Be consistent in using "edge" (not link)
- [x] Bold-face terms as you define them, e.g. **degree**
- [ ] Add an intuitive description of the Laplacian, or link to a lecture or other resource (perhaps https://simons.berkeley.edu/events/openlectures2014-fall-4 ?)
- [x] Avoid the word magical when talking about mathematics.  People are scared enough of mathematics as it is!

**Comment by stefanv** [comment]
@jni Please check to see how many of these are done.

**Comment by jni** [comment]
@stefanv I usually italicise, rather than bold, new terms. That's the way most of the book is written. I'll go over Ch6 with these in mind.
