### ISSUE TITLE
Feedback on FFT chapter

### ISSUE THREAD

**Issue by stefanv** [elegant-scipy/elegant-scipy#176]
From PW van der Walt:

_p2_
- [x] Frequency, in cycles per second, or Herz    ..... should be Hertz
- [x] Below figure think of it as an repeating signal of frequency

_p8_
- [x] There is, and it ts called the Discrete Fast Fourier Transform (discrete, because our recording consists of discrete measurements, and fast—because we're in a hurry!). The Fast Fourier Transform (FFT) tells us which frequencies or "notes" to expect in our signal.
- [x] This is a Discrete Fourier Transform calculated with the FFT algorithm, often called the FFT in stead of the DFT.
- [x] .... is called the Discrete or Fast Fourier Transform
- [x] The Fourier transform essentially tells us how to combine a set of sinusoids of varying frequency to form the input signal.
- [x] The Fourier series tells us this. The DFT results in the sampled input signal, also periodic. The Fourier Transform also handles nonperiodic signals.

_p12_
- [ ] You also used the square: 20log(x)=10log(x**2)
- [x] arbitrary periodic functions can be represented by trigonometric entities? The Fourier integral for non periodic functions is an infinite weighted sum of complex exponentials.
- [x] Consider that a naive calculation of the FFT takes operations. How come? Well, you have N (complex) sinusoids of different frequencies ( ),
- [x] This should read DFT, not FFT.
- [x] Something fell off the last sentence on this page.

**Comment by jni** [comment]
@stefanv how about clearing this checklist? ;)
