### ISSUE TITLE
requirements.txt and environment.yml out of sync

### ISSUE THREAD

**Issue by hdashnow** [elegant-scipy/elegant-scipy#217]
requirements.txt and environment.yml have different tools/versions in them. For example:
matplotlib>=2.0.0rc2 / matplotlib=1.5*
notedown>=1.4 / notedown==1.5

**Comment by stefanv** [comment]
2.0 is not yet available for Conda

**Comment by stefanv** [comment]
Yeah, I guess that'd work!  I'll leave this up to @jni or yourself

**Comment by hdashnow** [comment]
The following are in requirements.txt, but not in environment.yml, so I'm adding them:

ipython
astropy
jupytercontrib>=0.0.5
pillow
bs4
lxml

I'm also removing seaborn.

**Comment by jni** [comment]
Change ipython to jupyter. Or, if jupyter is already there, you should remove ipython altogether, since jupyter depends on it

**Comment by jni** [comment]
We can also get rid of astropy, that was for the auto histogram bins which is now in matplotlib proper.

**Comment by jni** [comment]
matplotlib 2.0 is available in conda-forge.
