### ISSUE TITLE
Quotes for the start of each chapter 

### ISSUE THREAD

**Issue by hdashnow** [elegant-scipy/elegant-scipy#243]
Some suggestions:

- [x] 1 Elegant NumPy: The Foundation of Scientific Python

"[NumPy] is everywhere. It is all around us. Even now, in this very room. You can see it when you look out your window or when you turn on your television. You can feel it when you go to work... when you go to church... when you pay your taxes."
— Morpheus, The Matrix

- [x] 2 Quantile normalization with NumPy and SciPy

“Distress not yourself if you cannot at first understand the deeper mysteries of Spaceland. By degrees they will dawn upon you.”
― Edwin A. Abbott, Flatland: A Romance of Many Dimensions

- [x] 3 Networks of Image Regions with ndimage

Tyger Tyger, burning bright,
In the forests of the night;
What immortal hand or eye,
Could frame thy fearful symmetry?
-- The Tyger, William Blake

- [x] 4 Frequency and the fast Fourier transform

“If you want to find the secrets of the universe, think in terms of energy, frequency and vibration.”
― Nikola Tesla

- [x] 5 Contingency tables using sparse coordinate matrices

Suggestion by @jni: "Fast is fine, but accuracy is everything. — Xenophon. Also, Wyatt Earp."

Better: "I like sparseness. There's something about that minimalist feel that can make something have an immediate impact and make it unique. I'll probably always work with that formula. I just don't know how." — Britt Daniel (Lead singer of Austin-based band Spoon. The band's guitarist is, get this: Greg Wilson.)

- [x] 6 Linear algebra in SciPy

"No one can be told what The Matrix is. You have to see it for yourself."
— Morpheus, The Matrix

- [x] 7 Function optimization in SciPy
Already has a quote

- [x] 8 Big Data in Little Laptop with Toolz

Gracie: A knife? This guy's twelve feet tall!
Jack Burton: Seven. Hey, don't worry, I can handle him.
— Big Trouble in Little China

**Comment by stefanv** [comment]
These are excellent :)

**Comment by stefanv** [comment]
Possible quotes from Big Trouble in Little China, for Ch 8:

Gracie: A knife? This guy's twelve feet tall!
Jack Burton: Seven. Hey, don't worry, I can handle him.

Jack Burton: What's in the flask, Egg? Magic potion?

**Comment by jni** [comment]
@hdashnow absolutely awesome. =D I'd move Morpheus to ch6 though?

We could also double up on Morpheus:

"NumPy is everywhere. It is all around us. Even now, in this very room. You can see it when you look out your window or when you turn on your television. You can feel it when you go to work... when you go to church... when you pay your taxes."

=P

@stefanv the first quote for ch8 is excellent, with bonus points for the source! The second one...?

**Comment by hdashnow** [comment]
Haha, fake quote, I love it. Yep, the matrix quote can just as easily move to 6. We're pretty matrix-happy in this book ;)

**Comment by hdashnow** [comment]
@stefanv, naively, I think the first quote is the best fit for the chapter. I'm going to have to go watch that movie so I understand the second quote though.

**Comment by stefanv** [comment]
The 2nd one was a stretch, let's do the first.  And I love the butchered matrix quote.

**Comment by jni** [comment]
- [ ] Epilogue

Let us make our future now, and let us make our dreams tomorrow's reality. — Malala Yousafzai

Ultimately, it comes down to taste. It comes down to trying to expose yourself to the best things that humans have done and then try to bring those things into what you’re doing. — Steve Jobs

Quality is not an act, it is a habit. — Aristotle

Quality means doing it right when no one is looking. — Henry Ford

One has to secrete a jelly in which to slip quotations down people's throats - and one always secretes too much jelly. — Virginia Woolf

I have offended God and mankind because my work didn't reach the quality it should have. — Leonardo da Vinci

Find people who will make you better. — Michelle Obama

Just try new things. Don't be afraid. Step out of your comfort zone and soar, all right? — Michelle Obama

**Comment by hdashnow** [comment]
I like the Spoon quote, but maybe just use the first half? "I like sparseness. There's something about that minimalist feel that can make something have an immediate impact and make it unique."

And my favourite for the epilogue is the Ford quote. Followed by Aristotle.

**Comment by jni** [comment]
Agreed about Spoon. I kinda liked the end because it's like, hey in this chapter we'll teach you how. =P But I can definitely agree that the start by itself can be more impactful. ;)

I also like the Ford quote but the source is less interesting, so I would lean towards Aristotle between the two. Let's see what @stefanv thinks. Thanks for your help picking! =)

**Comment by stefanv** [comment]
I also like the Ford quote!

**Comment by jni** [comment]
Good cos that's what I've put in my initial edits. Thanks for helping me decide! =)

**Comment by stefanv** [comment]
Thinking about it, it does sound a bit preachy too.  But perhaps an epilogue is a good place for that ;)  Maybe the Aristotle quote is less offensive that way, but: why would anyone think that quality is an act?

**Comment by jni** [comment]
Agreed. Actually I think the Jobs quote is the best because it ties in with a lot of themes that I want to develop in there, one of which is: do open source because you'll get feedback from the best people, people who are more experienced than you and will help you develop your taste.

**Comment by jni** [comment]
But Jobs is a polarising figure, even among the authors. ;)

**Comment by stefanv** [comment]
Going back to the ancients:

It is quality rather than quantity that matters. — Lucius Annaeus Seneca

**Comment by jni** [comment]
I found that one but found it less relevant than the other choices. And also much more commonly paraphrased today.

**Comment by stefanv** [comment]
In a slightly different direction:

“Any intelligent fool can make things bigger, more complex, and more violent. It takes a touch of genius — and a lot of courage to move in the opposite direction.” ― Ernst F. Schumacher

**Comment by stefanv** [comment]
Interesting, re Aristotle quote:

> “Excellence is an art won by training and habituation: we not act rightly because we have virtue or
> excellence, but rather have these because we have acted rightly; these virtues are formed in man by
> doing his actions; we are we repeatedly do. Excellence, then, is not an act but a habit.”
> – Will Durant, The Story of Philosophy (1926)

http://blogs.umb.edu/quoteunquote/2012/05/08/its-a-much-more-effective-quotation-to-attribute-it-to-aristotle-rather-than-to-will-durant/
