### ISSUE TITLE
Add captions to all figures

### ISSUE THREAD

**Issue by hdashnow** [elegant-scipy/elegant-scipy#254]
Based on this build: http://orm-atlas2-prod.s3.amazonaws.com/pdf/088777745f637e41c2db04cd5b60cfb5.pdf

Most of the plots in these chapters are missing captions:
- [x] ch3
- [x] ch4
- [x] ch5

ch6, 7 and 8 have a few missing captions:
- [ ] ch6 page 205, 210
- [ ] ch7 page 214, 217, 218, 222, 229, 231, 232, 234
- [ ] ch8 page 251, 252, 255, 257

**Comment by jni** [comment]
@stefanv for ch6 p205 (of the pdf, p202 of the book), the caption is actually in the source markdown, but not in the generated book. Any ideas?

**Comment by jni** [comment]
Ditto for p207/205 (sparse plot_connectome), and basically I think all of the missing captions mentioned by @hdashnow...!

**Comment by stefanv** [comment]
Fixed; the caption cruncher only handled single-line captions before.
