### ISSUE TITLE
Weird URL processing error

### ISSUE THREAD

**Issue by jni** [elegant-scipy/elegant-scipy#287]
Some processing happening downstream of html is messing with the wormatlas URL in chapter 3:

<img width="670" alt="screen shot 2017-05-12 at 8 00 41 pm" src="https://cloud.githubusercontent.com/assets/492549/25996424/97fec9ca-375a-11e7-924f-42bc5e907d0e.png">

Not sure whether this is fixed in recent builds.

**Comment by stefanv** [comment]
This is fixed in the latest build, I just forgot to do a new upload.
