### ISSUE TITLE
Typos in preface

### ISSUE THREAD

**Issue by stefanv** [elegant-scipy/elegant-scipy#295]
- [x] Where we have
sourced code snippets from other people, the code was generally be under a
permissive open license of some variety (although not necessarily BSD).
- [x] There are a whole bunch of other great GitHub features, but we will
leave many them for you to discover and some for you to read in later chapters.
- [x] And, if we each contribute a little bit, together we built a lot.
- [ ] (Capitalization) A Touch of Whimsy with your Py

**Comment by jni** [comment]
I'm punting on title case — it's a major consistency issue where we have to look at headings throughout the book. And I don't think it's very critical.

**Comment by stefanv** [comment]
Yup, that's okay by me.
