### ISSUE TITLE
Give away 25 copies at SciPy2017!

### ISSUE THREAD

**Issue by stefanv** [elegant-scipy/elegant-scipy#308]
Leave a comment on this issue if you'd like to join the 25-book raffle at SciPy 2017.

**You have to be physically present on Thursday afternoon at the [lightning talks](https://scipy2017.scipy.org/ehome/220975/493422/) to qualify!**

![image](https://user-images.githubusercontent.com/45071/27242378-bec871da-5291-11e7-8641-159e2aebd990.png)

**Comment by josephhardinee** [comment]
Sure. Name: Joseph Hardin

**Comment by Jeecie** [comment]
Interested!

**Comment by randirl17** [comment]
#scipy2017 is off to a great start!

**Comment by bheklilr** [comment]
Count me in

**Comment by pruddle** [comment]
Interested!  Paul Ruddle

**Comment by eramirem** [comment]
I'm in!

**Comment by jcrist** [comment]
I'm in!

**Comment by mudspringhiker** [comment]
Awesome!

**Comment by ddasilva** [comment]
I'm in!

**Comment by stembl** [comment]
Comment left

**Comment by amueller** [comment]
I wants!

**Comment by ashley-dsci** [comment]
I'm interested!

**Comment by rishikeshd** [comment]
Im interested

**Comment by mwcraig** [comment]
h*ck yes!

**Comment by DarthDippy** [comment]
![](https://media.makeameme.org/created/count-me-in-lsgm55.jpg)

**Comment by ajford** [comment]
Totally interested!

**Comment by wfspotz** [comment]
Awesome!

**Comment by drsuuzzz** [comment]
Pick me!

**Comment by scollis** [comment]
Pick me pick me! Scott collis

**Comment by mandynluna** [comment]
ME ME ME!!!

**Comment by katyhuff** [comment]
Me me me! Katy Huff

**Comment by julesfowler** [comment]
Put me in the raffle, please -- I'd love a book.

**Comment by jonathanrocher** [comment]
I want one! Please?

**Comment by mepa** [comment]
Interested

**Comment by srcole** [comment]
I WANT

**Comment by kyleniemeyer** [comment]
Ooh I am definitely interested, and will be there!

**Comment by katepol** [comment]
plus one

**Comment by ricleal** [comment]
Yep, I'm in... Me and the 703 Scipyers :)

**Comment by ahgnaw** [comment]
Count me in!

**Comment by jcfr** [comment]
Thanks for organizing this. Count me in :fireworks:

**Comment by fzmolina** [comment]
Count me in please! Faviola Molina

**Comment by rcjackson** [comment]
Count me in!

**Comment by alejandrox1** [comment]
comment comment comment

**Comment by lle624** [comment]
*raises hand*

**Comment by leosartaj** [comment]
I am in.

**Comment by kthyng** [comment]
Me too!!

**Comment by dhpadovani** [comment]
Count me in!!

**Comment by zssherman** [comment]
Count me in! : Zach Sherman

**Comment by jonathan-owens** [comment]
Me too!

**Comment by tonyyli** [comment]
Definitely in! (Tony Li)

**Comment by Anyulund** [comment]
I would love one. Seems like I'm out of luck for 25 copies :)

**Comment by jpasq3nthought** [comment]
Im in!

**Comment by henrykironde** [comment]
Yes.

**Comment by lmcinnes** [comment]
Count me in.

**Comment by mjbrodzik** [comment]
Yes please would love a copy

**Comment by stargaser** [comment]
Yes please!

**Comment by ivanov** [comment]
![It's a trap!](http://media-cache-ec0.pinimg.com/736x/57/70/ac/5770ac453750fd3e6d5f7d197004882c.jpg)

...or, I mean... yes please! :)

**Comment by ChrisDolph** [comment]
Pick me!

**Comment by vnellore** [comment]
Yes, please!

**Comment by cbcunc** [comment]
I'd love one!

**Comment by lucarizzi** [comment]
I am in!! 

Luca Rizzi

**Comment by clovermike** [comment]
in!

**Comment by nguyenmp** [comment]
Me too!

**Comment by jamespreed** [comment]
I am in as well!

**Comment by arcticbarra** [comment]
I'm in!

**Comment by monaldoj** [comment]
#comment

**Comment by shindhelm** [comment]
#42

**Comment by IsabelAverill** [comment]
In French: Comment?

**Comment by gforsyth** [comment]
I'm in!

**Comment by stsievert** [comment]
I'm in!

**Comment by israelzuniga** [comment]
Interested! 

Israel.

**Comment by sigma23** [comment]
Can't wait to read it!

**Comment by clarka34** [comment]
Me too!

**Comment by erikjsvensk** [comment]
Please count me in, thanks!

**Comment by rsignell-usgs** [comment]
Yes please! :smile_cat:

**Comment by prsutherland** [comment]
Count me in! Paul Sutherland

**Comment by CRobGIS-RS** [comment]
Yes Sir!

**Comment by bdkech** [comment]
Yes please!!

**Comment by giesberge** [comment]
In, Eric Giesberg

**Comment by mwickert** [comment]
Sounds interesting. I'm in!

**Comment by vrx-** [comment]
yes please!

**Comment by jakespracher** [comment]
Comment

**Comment by joshnankivel** [comment]
Yes please!

**Comment by kr1m** [comment]
```this is a comment ```

**Comment by RavingMadScientist** [comment]
Free boox plz? :)

**Comment by mollyhardman** [comment]
Count me in!!

**Comment by vestuto** [comment]
can has book plz?

**Comment by gsever** [comment]
up, Gökhan.

**Comment by ijstokes** [comment]
I'm in. I love #SciPy.

**Comment by acrogenesis** [comment]
Woohoo! Cheers

**Comment by ocefpaf** [comment]
:+1:

**Comment by DJCordhose** [comment]
send it to me!

**Comment by chendaniely** [comment]
there's a snake in my boot!

**Comment by cgosmeyer** [comment]
Comment!

**Comment by jGaboardi** [comment]
Want!

**Comment by ZZZWENG** [comment]
Count me in!

**Comment by jrleeman** [comment]
I'm in!

**Comment by moorepants** [comment]
how elegant

**Comment by dopplershift** [comment]
🥇 Me too!

**Comment by kstory8** [comment]
This looks great!

**Comment by namurphy** [comment]
Please sign me up too!

**Comment by untzag** [comment]
comment ❤️

**Comment by loriab** [comment]
interested

**Comment by asmeurer** [comment]
I'm not going to win

**Comment by johnh2o2** [comment]
Would love a copy!

**Comment by bmcfee** [comment]
Is this where I can win an Elephant SciPy?

![Elephant](https://media.giphy.com/media/AUYhIMdGrg23e/giphy.gif)

**Comment by adelcast** [comment]
yeah, I am in!

**Comment by tsansom** [comment]
#Scipy2017

**Comment by ChrisBarker-NOAA** [comment]
Is this an elegant comment?

Thanks for making it Open Source!

**Comment by DJCordhose** [comment]
does it help to leave two comments?

**Comment by mollyrossow** [comment]
I'm interested!

**Comment by zachdicus** [comment]
Definitely.

**Comment by jjhelmus** [comment]
Does it include any machine learning on waffles?

**Comment by quant911** [comment]
Fantastic topic. I am interested. Thanks.

**Comment by kyrubas** [comment]
What did the mobster electron say to the wire?


You'll never catch me copper... I'm going to ground!
-Theodore Markulin

**Comment by fbudin69500** [comment]
It looks awesome.

**Comment by mlange05** [comment]
Yes, please.

**Comment by rdk1024** [comment]
Everybody wants one.

**Comment by narendramukherjee** [comment]
I'm in

**Comment by ajkuck** [comment]
I'm interested!

**Comment by ssunkara1** [comment]
I'm in too!! :)

**Comment by scott-lewis-nsidc** [comment]
I'm interested, too!

**Comment by cmannfolk** [comment]
I'm interested.

**Comment by ashammad** [comment]
Me too in pls

**Comment by penar929** [comment]
I'm interested

**Comment by proteasome** [comment]
here and there

**Comment by BProvencher** [comment]
Want!

**Comment by guyer** [comment]
Yes

**Comment by stefanv** [comment]
Thanks, everyone!  That was fun!

The winners are:

1. zachdicus
2. asmeurer
3. jrleeman
4. jonathanrocher
5. clarka34
6. katyhuff
7. ZZZWENG
8. lucarizzi
9. leosartaj
10. JeanBilheux
11. jcfr
12. cbcunc
13. kyleniemeyer
14. ashley-dsci
15. vrx-
16. arcticbarra
17. giesberge
18. cgosmeyer
19. DarthDippy
20. erikjsvensk
21. Jeecie
22. CRobGIS-RS
23. mudspringhiker
24. ChrisDolph
25. ocefpaf
26. jamespreed

(We had to generate 26 names, because someone wasn't there to receive their copy.)

The raffle script is here: https://gist.github.com/stefanv/87c866f3bda2a1f1f2d23380cdf4dd9f  (let's just consider any bugs and deficiencies part of the secret raffling hashing algorithm ;).

**Comment by jcfr** [comment]
Thanks for the book @stefanv and also thanks for making it available online 👍

**Comment by arcticbarra** [comment]
Thanks for the book @stefanv!

**Comment by stefanv** [comment]
@jcfr @arcticbarra No problem!  If you like it, let me know and I may be able to get hold of a color copy for you.

**Comment by stefanv** [comment]
For those of you who didn't win books, I've put an HTML built copy here:

https://www.dropbox.com/s/cw49dk1gj6r389i/elegant-scipy-2017-07-13_15-18-54.zip?dl=0

**Comment by vrx-** [comment]
Muchas gracias for the book @stefanv!
