### ISSUE TITLE
Prepare for book signing

### ISSUE THREAD

**Issue by stefanv** [elegant-scipy/elegant-scipy#309]
1. Come up with 25 phrases to write in the beginning of each book (I'll also label them by number, e.g. #3/25):
 - "Elegantly yours"
 - "May elegance be with you"
 - "To elegant or not to elegant, that is *NOT* the question! That's not even *A* question!"
 - "Happy hacking"

2. Talk; mention:
 - That you can build your own book (Jupyter notebooks, HTML, or read directly on GitHub in Markdown)

**Comment by jni** [comment]
1.

- You are now the proud owner of one of the last books printed by O'Reilly. (=P)
- Never Stop Improving
- Elegant code for a more civilized age

2.

- Should we revisit building and committing the notebooks so they are rendered on GH?

**Comment by jni** [comment]
"Enjoy Elegant SciPy on the patio, in the car, or on the boat. Wherever good times are had!" (This is a reference to Bender on Futurama. ;)

**Comment by jni** [comment]
"Enjoy responsibly."

**Comment by jni** [comment]
@stefanv https://github.com/elegant-scipy/notebooks Use if you find useful. Probably only real option for Windows users for now...!

**Comment by jni** [comment]
- "Let's science the shit out of this Python" (xref The Martian)
- "Use prior to operating heavy machinery for heightened awareness"
- "WARNING: Some nations may consider this book a performance-enhancing drug"

**Comment by jni** [comment]
- "Limited edition Platinum version (ie everything is black and white)" (OMG I just realised how horrible that is for Ch7)
- "Elegant SciPy gives you wings"
- "If you like the networking in this conference, wait till you see the network analysis in chapter 6!"
- "Feel the data *flow* through you (in Chapter 8)"

**Comment by jni** [comment]
- "Elegance and SciPy — a potent combination." (Zapp Brannigan) (Or "Python and Science")
- "Keep calm and use SciPy"
