### ISSUE TITLE
Readability improvement for quotations in the Kindle edition

### ISSUE THREAD

**Issue by dshlai** [elegant-scipy/elegant-scipy#321]
In my kindle edition from Amazon:

![image](https://user-images.githubusercontent.com/695260/31530151-cd5401c4-b010-11e7-9810-750226479b84.png)

and format like this:

![image](https://user-images.githubusercontent.com/695260/31530245-b8ff1974-b011-11e7-96b1-2aaf454ea65e.png)

All the quotations clustered together without paragraph spacing. This hurts readability.  Is it possible to add paragraph spacing between quotations and texts?

**Comment by stefanv** [comment]
Thanks for the report; this has been relayed to O'Reilly.
