### ISSUE TITLE
Wrong syntax for exponentiation

### ISSUE THREAD

**Issue by 0xB4DF4C3D** [elegant-scipy/elegant-scipy#342]
First of all, I might need to say that I'm a non-English speaker so some of my expressions could be crude.

I'm reading chapter 1 now, and I faced with this sentence:

> First, we multiply by 10^9. Because counts (C) is an ndarray, we can use broadcasting. If we multiple an ndarray by a single value, that value is broadcast over the entire array.

But, you know the `^` operator in Python means not exponentiation but the exclusive or. so it'll be 3 not 1,000,000,000. If we want to do what we expect, then we should `**` operator instead of `^`.

Thanks

**Comment by 0xB4DF4C3D** [comment]
Oh, I found that someone already issued this at #228. So I close this.

**Comment by jni** [comment]
@0xB4DF4C3D note that the sentence you refer to has `$` surrounding it. This is because the rendering is LaTeX, not Python. I've looked at the chapter again and all of the Python code is correctly either `10**9` or `1e9`.

Sorry for the confusion but thank you for reading our book!
