### ISSUE TITLE
import TCGA melanoma data in chapter 1

### ISSUE THREAD

**Issue by crazyhyz** [elegant-scipy/elegant-scipy#344]
The data folder doesn't contain 'counts.txt'. There's a file 'countx.txt.bz2'. The book's code doesn't work.

filename = 'data/counts.txt'

**Comment by crazyhyz** [comment]
figured out.
import bz2
and use bz2.open

**Comment by jni** [comment]
@crazyhyz thanks for the report! Actually it's "intended", in that you are supposed to run "make all" before doing this stuff — the Makefile contains the command to unzip the file. But, if `bz2.open` works transparently, that's a better solution! I'm going to reopen this as a reminder to change that line and the makefile. Thanks again!
