### ISSUE TITLE
Question about Exrcise in Chapter 2

### ISSUE THREAD

**Issue by afettouhi** [elegant-scipy/elegant-scipy#347]
At the end of Chapter 2, there is a short exercise mentioned and I am trying to figure it out but am I not sure I understand it quite right. In the first part you want us to take a bootstrap sample of the genes used using the `np.random.choice` function as given in the hint. Does that mean for each column in the `patients.csv`? Like this for example?

```python
# Creating bootstrap samples
n_random_clusters = np.random.choice(patients['original-clusters'], replace=True) 
```

**Comment by jni** [comment]
Hi @afettouhi, and thank you for your interest in our book!

Samples are *per clustering*, not per patient. So you should do something like:

```python
sample_indices = np.random.choice(np.arange(expr.shape[0]),
                                  size=expr.shape[0], replace=True)
bootstrapped_counts = counts[sample_indices, :]
...  # normalize, cluster
cluster_ids = fcluster(...)
for cid in np.unique(cluster_ids):
    mask = (cluster_ids == cid)[np.newaxis, :]
    co_cluster_matrix[mask * mask.T] += 1
```

**Comment by jni** [comment]
I hope this helps! I'm going to close this for now but please keep asking questions! =)

**Comment by afettouhi** [comment]
I don't think I quite understand what you mean by _per clustering_?

**Comment by jni** [comment]
You sample the rows, you cluster. Then you sample the rows, and you cluster again. Repeat this many times. Does that make sense?

**Comment by afettouhi** [comment]
The sample rows would the be the `yr` variables?

**Comment by jni** [comment]
no, `yr` is already clustered sample rows. Initially, sample rows are just 0, 1, 2, ..., n_rows. (The call to `np.arange`, above.) n_rows is the number of rows in the counts table, or counts.shape[0].

**Comment by afettouhi** [comment]
OK, you lost me there. What part of the data do I need to perform the `np.random.choice` on?

**Comment by jni** [comment]
Is the code above not clear? You sample row indices and then you get a bootstrapped counts matrix...?

**Comment by afettouhi** [comment]
No it isn't to me at least. My issue is what the `expr` in `expr.shape[0]`? What data are you refering to?

**Comment by jni** [comment]
Oh apologies, I’m thinking of Ch1. That should be counts, not expr

**Comment by afettouhi** [comment]
OK, that helps. this is how far I have gotten now with the code snippet you provided

```python
sample_indices = np.random.choice(np.arange(counts.shape[0]),
                                  size=counts.shape[0], replace=True)
bootstrapped_counts = counts[sample_indices, :]

log_bootstrapped_counts_normalized = quantile_norm_log(bootstrapped_counts)
bootstrapped_counts_log = np.log(bootstrapped_counts + 1)
bootstrapped_counts_var = most_variable_rows(bootstrapped_counts_log, n=1500)

yr, yc = bicluster(counts_var, linkage_method='ward',
                   distance_metric='euclidean')
with plt.style.context('style/thinner.mplstyle'):
    plot_bicluster(counts_var, yr, yc)
...  # normalize, cluster

from scipy.cluster.hierarchy import fcluster
n_clusters = 3
threshold_distance = (yc[-n_clusters, 2] + yc[-n_clusters+1, 2]) / 2
cluster_ids = fcluster(yc, threshold_distance, 'distance')
for cid in np.unique(cluster_ids):
    mask = (cluster_ids == cid)[np.newaxis, :]
    co_cluster_matrix[mask * mask.T] += 1
```

**Comment by jni** [comment]
You’ll need to create co_cluster_matrix using np.zeros as specified in the hint. It’s a square matrix with the number of patients. You are counting how many times patients end up in the same cluster.

To be honest the paper methods section was not that detailed so this is *my* interpretation of what you should do. It probably helps to read the paper and supplementary methods!

**Comment by afettouhi** [comment]
What hint are you referring to? The hint in book talks about how to create bootstrap samples. Are talking about the 3rd sub-question in the exercise?
