### ISSUE TITLE
Dependency management: environment.yml requires old versions

### ISSUE THREAD

**Issue by rossbar** [elegant-scipy/elegant-scipy#349]
According to the [conda environment docs](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html) the `environment.yaml` requires the use of old versions of many packages (1.12 for numpy, 2.0 for matplotlib, etc.)

This also means that the `environment.yaml` is actually out-of-sync with the `requirements.txt`, which takes the latest version for most libraries. It seems there have been issues with this in the past (#217).

I would propose the following:

 1. Create an environment using the current release of the dependencies
 2. Verify that the building/running of the jupyter notebooks is successful
 3. Modify both `environment.yaml` and `requirements.txt` so that they are consistent.
 4. Verify that all changes result in consistent, working environments with `conda` and `venv` independently

I'll take a look at this. Further suggestions (setting up a circleci?) are welcome!

**Comment by stefanv** [comment]
@rossbar Making those consistent should definitely be done.  We have a CI [Wercker](https://app.wercker.com/elegant-scipy/elegant-scipy/runs/build/5dd717598e18590008b1c4a7?step=5dd71789f947d10009368771), so let me know if you have any problems.
